services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-app
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-cache:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/userdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=wtpassword
      - SPRING_AUTH_DATASOURCE_URL=jdbc:mysql://auth-db:3306/authdb?createDatabaseIfNotExist=true
      - SPRING_AUTH_DATASOURCE_USERNAME=root
      - SPRING_AUTH_DATASOURCE_PASSWORD=authpassword
      - SPRING_REDIS_HOST=redis-cache
      - SPRING_REDIS_PORT=6379

  auth-db:
    image: mysql:8.0
    container_name: auth-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: authpassword
      MYSQL_DATABASE: authdb
    ports:
      - "3307:3306"
    volumes:
      - auth-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: wtpassword
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  mysql-data:
  redis-data:
  auth-data: